import './globals.sass';
import Nav from '@/app/components/nav/nav';
import TopBar from '@/app/components/topBar/topBar';
import BlurCircles from '@/app/components/blurCircles/blurCircles';
import BottomBar from '@/app/components/bottomBar/bottomBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="body">
        <BlurCircles />
        <div className="wrapper">
          <TopBar />
          <Nav />
          <main className="children">{children}</main>
          <BottomBar />
        </div>
      </body>
    </html>
  );
}
